### ISSUE TITLE
使用该模板创建启动失败，日志报错 $PATH未找到

### ISSUE THREAD

**Issue by liuwanlong** [natfrp/unraid-docker-templates#1]
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/28746574/209519128-1af7ea08-8644-4ecb-b788-531c822367f7.png">
<img width="480" alt="image" src="https://user-images.githubusercontent.com/28746574/209519203-be5aad2c-a5d5-4c18-b7c8-7b0da705c1ae.png">

**Comment by fakeboboliu** [comment]
我无法复现此问题，如果您仍存在此问题的话，请考虑截图隧道创建结果页（也就是这一页）共我们参考：
![图片](https://user-images.githubusercontent.com/7552030/209537623-6778ce6c-2c6c-4d20-bdc3-78bf255a32c4.png)

另，请删除隧道id间的空格

**Comment by liuwanlong** [comment]
> 

<img width="909" alt="image" src="https://user-images.githubusercontent.com/28746574/209538015-b47f8d13-3633-4ed5-a628-d049f96c107f.png">
空格已删除 还是那个错误 辛苦再看下

**Comment by fakeboboliu** [comment]
可能是 image 版本没有更新？此前某个老版本 image 在 unraid 上可能会有这个问题，但我没有在截图中看到我在期待的 image hash，所以并不能确定这一点。

如果不在删除容器时选择删除 image，unraid 不会在下次新建时更新镜像。

如果成功更新的话，您应当看到创建结果页中上方框内的内容与我上面的图基本相同。

**Comment by liuwanlong** [comment]
> 可能是 image 版本没有更新？此前某个老版本 image 在 unraid 上可能会有这个问题，但我没有在截图中看到我在期待的 image hash，所以并不能确定这一点。
> 
> 如果不在删除容器时选择删除 image，unraid 不会在下次新建时更新镜像。
> 
> 如果成功更新的话，您应当看到创建结果页中上方框内的内容与我上面的图基本相同。

那可能是阿里云镜像源的docker版本不对 过几天我再试下

**Comment by fakeboboliu** [comment]
> 那可能是阿里云镜像源的docker版本不对 过几天我再试下

您如果手工替换了 `registry.cn-hongkong.aliyuncs.com/natfrp/frpc` 镜像，此镜像的版本应当是正确的 。

请考虑删除容器时勾选删除镜像，然后重新创建。

**Comment by liuwanlong** [comment]
> > 那可能是阿里云镜像源的docker版本不对 过几天我再试下
> 
> 您如果手工替换了 `registry.cn-hongkong.aliyuncs.com/natfrp/frpc` 镜像，此镜像的版本应当是正确的 。
> 
> 请考虑删除容器时勾选删除镜像，然后重新创建。

感谢 我把unraid docker阿里云镜像加速去除 采用梯子代理重新安装，已成功启动✅

**Comment by fakeboboliu** [comment]
> 把unraid docker阿里云镜像加速去除 采用梯子代理重新安装，已成功启动✅

啊，阿里云的docker镜像加速是比较尴尬啦……但是我们的镜像很小（<5MiB），不用镜像加速即使再慢也可以很快下完的。

果然还是把默认的镜像地址改成阿里云香港吧，感谢您的 issue。
